[package]
name = "trim-in-place"
version = "0.2.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/magiclen/trim-in-place"
homepage = "https://magiclen.org/trim-in-place"
keywords = ["string", "trim", "in-place"]
categories = ["no-std"]
description = "In-place trimming strings."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "trim"
harness = false

[[bench]]
name = "no_trim"
harness = false
